name: New Algorithm
description: 'Sugerir nuevos algoritmos, proponer mejoras, debatir nuevas ideas de algoritmos'
title: '[NEW ALGORITHM]: '
labels: ['New Algorithm']
body:
  - type: markdown
    attributes:
      value: |
        ## Esta plantilla de 'Issue' es para proponer nuevos algoritmos
        ## Asegurese de que su tema no es un duplicado y de que sigue nuestras [directrices de contribucion](https://github.com/Bryan-Herrera-DEV/Algorithms-Typescript/blob/main/CONTRIBUTING.md)
  - type: textarea
    id: description
    attributes:
      label: Descripcion del algoritmo
      description: Describa el algoritmo, su uso de manera sencilla y si es posible su complejidad matematica
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Referencias y links
      description: Si usted ah tomado la idea del algoritmo ponga los enlaces aqui, o si tiene enlaces que expliquen de una manera mas extensa el mismo
    validations:
      required: true
